### ISSUE TITLE
Improve discoverability on HF

### ISSUE THREAD

**Issue by NielsRogge** [kongds/E5-V#1]
Hi,

Niels here from the open-source team at Hugging Face. It's great to see you're releasing models on HF, I found your work through the paper page: https://huggingface.co/papers/2407.12580.

However, the model is currently not discoverable from the paper, would you be able to link it?

Here's how to do that: https://huggingface.co/docs/hub/en/model-cards#linking-a-paper

Let me know if you need any help!

Thanks also for using LLaVa-NeXT, it's a model which I've contributed to the Transformers library :)

Cheers,

Niels
ML Engineer @ HF 🤗

**Comment by kongds** [comment]
Thanks for your advice.
I have updated the README for releasing the model, which now correctly shows the paper tag.

**Comment by NielsRogge** [comment]
Thank you @kongds!
