### ISSUE TITLE
Discrepancy in CIRR Test Set Size

### ISSUE THREAD

**Issue by SanghyeokSon** [kongds/E5-V#10]
Thank you for sharing such an impressive work! I have a question regarding the dataset size.

According to the CIRR dataset paper, the test set contains 2,316 images.
However, the test set used in the Hugging Face dataset royokong/cirr_imgs contains 2,315 images. 
Where does this discrepancy come from?

**Comment by kongds** [comment]
Thank you for your interest in our work.

The differences are from the original CIRR dataset.

You can check the size of the original CIRR test images by following these steps

```bash 
wget https://raw.githubusercontent.com/Cuberick-Orion/CIRR/refs/heads/cirr_dataset/image_splits/split.rc2.test1.json
python <<EOF
import json
test_imgs = json.load(open('./image_splits/split.rc2.test1.json'))
print('test img size:', len(test_imgs))
EOF
```

**Comment by SanghyeokSon** [comment]
My question has been resolved. Thank you for your prompt response, and once again, I appreciate you sharing such an excellent work!

**Comment by SanghyeokSon** [comment]
My question has been resolved. Thank you for your prompt response, and once again, I appreciate you sharing such an excellent work!
