### ISSUE TITLE
code for clustering

### ISSUE THREAD

**Issue by haoxiangzhao12138** [kongds/E5-V#13]
<img width="727" alt="image" src="https://github.com/user-attachments/assets/0ae2677a-321e-44cf-9fe9-7fe1cddf28fa">

Could you kindly provide the code used for clustering in the paper? Was it based on k-means for clustering and t-SNE for visualization? The results I achieved with my own implementation differ significantly from those in the paper.

**Comment by kongds** [comment]
For the visualization, we use the code from `modality gap`. You can find the implementation at https://github.com/Weixin-Liang/Modality-Gap/blob/8e20cb24efa4c5f89aad694f2f65eb43ffc46d10/Figure_1_Modality_Gap/repr_clip.ipynb#L171.
```python
import torch
import numpy as np
from matplotlib import pyplot as plt

all_img_features = torch.load('[coco_img_embs.pt]').cpu().numpy()
all_text_features = torch.load('[coco_text_embs.pt]').cpu().numpy()

def svd(X, n_components=2):
    # using SVD to compute eigenvectors and eigenvalues
    # M = np.mean(X, axis=0)
    # X = X - M
    U, S, Vt = np.linalg.svd(X)
    # print(S)
    return U[:, :n_components] * S[:n_components]

features_2d = svd(np.concatenate([all_img_features, all_text_features], 0))

plt.figure(figsize=(5, 5))
plt.scatter(features_2d[:len(all_img_features), 0], features_2d[:len(all_img_features), 1], c='red')
plt.scatter(features_2d[len(all_img_features):, 0], features_2d[len(all_img_features):, 1], c='blue')
```

**Comment by haoxiangzhao12138** [comment]
thank you ！！！！
