### ISSUE TITLE
Index Out of range Error when running the model

### ISSUE THREAD

**Issue by XMHZZ2018** [kongds/E5-V#7]
Thanks team for this great work! 

When I run the model, I have met "IndexError: index out of range". When I take a close look, it seems that it's due to the image_token_index (it's starting from 0) is larger than vocab_size.

"image_token_index": 128256,
"vocab_size": 128256

Could you please help me with this? Thanks!

**Comment by XMHZZ2018** [comment]
I try to fix it by resizing model's token embedding to 128,257 and I could run it now. Not sure whether this is a correct fix.

**Comment by kongds** [comment]
Thank you for your interest in our work.
It seems to be caused by a new version of `transformers`. You can resolve this error by installing an older version using `pip install transformers==4.41.2` in requirement.txt. (Resizing the token embedding also work.)

**Comment by XMHZZ2018** [comment]
Got it! Thanks a lot for your quick reply!
