### ISSUE TITLE
release Phi-3 based model

### ISSUE THREAD

**Issue by oferidan1** [kongds/E5-V#8]
Hi,
Thanks for sharing your great work!
Do you have plans to release your Phi-3 based model?
Thanks,
Ofer

**Comment by kongds** [comment]
Thank you for your interest in our work.

Since I am currently checked out, I do not have access to the previously stored model weights. Additionally, I do not have the computational resources to reproduce this experiment at the moment. I apologize for the inconvenience.

**Comment by oferidan1** [comment]
Hi, thanks for getting back to me.
Can you please share phi-3 training details with me? For example, lora
config , target_modules , etc.
I would like to reproduce this experiment.
Thanks in advance,
Ofer

**Comment by kongds** [comment]
The training details are as follows:

Chat template: `<|user|>\n{}<|end|>\n<|assistant|>\n` (replace {} with the training or evaluation prompt)
Model: `microsoft/Phi-3-vision-128k-instruct`

Other settings are the same with  LLaVA, which can be found in 
https://github.com/kongds/E5-V/blob/e4e4662bb65b0c393c901c6de0a05d317dd542ec/run.sh#L1-L44

**Comment by oferidan1** [comment]
Thanks alot for your feedback.
I think that target_modules "q_proj,k_proj,v_proj" are part of CLIP image
encoder in phi-3, while qvk_proj is of LM.
Is this correct?
Thanks and regards.

**Comment by kongds** [comment]
Since we train only the LLM of MLLM, the target modules ‘q_proj,k_proj,v_proj,o_proj,gate_proj,down_proj,up_proj’ are in the LLM. (We will remove the image encoder during training)
